version: '3.7'

networks:
  todolist:
    driver: bridge
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=micro-todolist
      - TZ=Asia/Shanghai
    ports:
      - "3306:3306"
    networks:
      - todolist